/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 midoriya_rigged_hatchxr.glb
Author: nitwit.friends (https://sketchfab.com/nitwit.friends)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/midoriya-rigged-hatchxr-afc0941d31b746adb18baaf243d12fb1
Title: Midoriya Rigged (HatchXR)
*/

import { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { UseCharacterAnimations } from '../provider/CharacterAnimations'

export function Midoriya(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./canvas/midoriya.glb')
  const { actions, names } = useAnimations(animations, group)
  const { setAnimations, animationIndex } = UseCharacterAnimations()
  useEffect(() => {
    setAnimations(names)
  }, [names])

  useEffect(() => {
    actions[names[animationIndex]].reset().fadeIn(0.5).play()
    return () => {
      actions[names[animationIndex]].fadeOut(0.5).play()
    }
  }, [animationIndex])

  return (
    <>
      <group ref={group} {...props} dispose={null}>
        <group name='Sketchfab_Scene'>
          <group
            name='Sketchfab_model'
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.702}
          >
            <group
              name='fbx_mergefbx'
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.025}
            >
              <group name='Object_2'>
                <group name='RootNode'>
                  <group name='Object_4'>
                    <primitive object={nodes._rootJoint} />
                    <group name='Object_6' rotation={[-Math.PI / 2, 0, 0]} />
                    <group name='SK_pl01_001' rotation={[-Math.PI / 2, 0, 0]} />
                    <skinnedMesh
                      name='Object_7'
                      geometry={nodes.Object_7.geometry}
                      material={materials.MII_Pl01001_hair}
                      skeleton={nodes.Object_7.skeleton}
                    />
                    <skinnedMesh
                      name='Object_8'
                      geometry={nodes.Object_8.geometry}
                      material={materials.MII_Pl01001_eyeshadow}
                      skeleton={nodes.Object_8.skeleton}
                    />
                    <skinnedMesh
                      name='Object_9'
                      geometry={nodes.Object_9.geometry}
                      material={materials.MII_Pl01001_face_GPA_TM}
                      skeleton={nodes.Object_9.skeleton}
                    />
                    <skinnedMesh
                      name='Object_10'
                      geometry={nodes.Object_10.geometry}
                      material={materials.MII_Pl01001_mask}
                      skeleton={nodes.Object_10.skeleton}
                    />
                    <skinnedMesh
                      name='Object_11'
                      geometry={nodes.Object_11.geometry}
                      material={materials.MII_Pl01001_eye_GPD}
                      skeleton={nodes.Object_11.skeleton}
                    />
                    <skinnedMesh
                      name='Object_12'
                      geometry={nodes.Object_12.geometry}
                      material={materials.MII_Pl01001_body_GPA_TM}
                      skeleton={nodes.Object_12.skeleton}
                    />
                    <skinnedMesh
                      name='Object_13'
                      geometry={nodes.Object_13.geometry}
                      material={materials.MII_Pl01001_Lhand_GPB_hideB_TM}
                      skeleton={nodes.Object_13.skeleton}
                    />
                    <skinnedMesh
                      name='Object_14'
                      geometry={nodes.Object_14.geometry}
                      material={materials.MII_Pl01001_hood_hideC}
                      skeleton={nodes.Object_14.skeleton}
                    />
                    <skinnedMesh
                      name='Object_15'
                      geometry={nodes.Object_15.geometry}
                      material={materials.MII_Pl01001_RarmbreakB_GPC_ShideA_TM}
                      skeleton={nodes.Object_15.skeleton}
                    />
                    <skinnedMesh
                      name='Object_16'
                      geometry={nodes.Object_16.geometry}
                      material={materials.MII_Pl01001_Rhand_GPC_hideA_TM}
                      skeleton={nodes.Object_16.skeleton}
                    />
                    <skinnedMesh
                      name='Object_17'
                      geometry={nodes.Object_17.geometry}
                      material={materials.MII_Pl01001_LarmbreakB_GPB_ShideB_TM}
                      skeleton={nodes.Object_17.skeleton}
                    />
                    <skinnedMesh
                      name='Object_18'
                      geometry={nodes.Object_18.geometry}
                      material={materials.MII_Pl01001_LarmbreakA_GPA_ShideB_TM}
                      skeleton={nodes.Object_18.skeleton}
                    />
                    <skinnedMesh
                      name='Object_19'
                      geometry={nodes.Object_19.geometry}
                      material={materials.MII_Pl01001_Rarm_GPA_hideA_TM}
                      skeleton={nodes.Object_19.skeleton}
                    />
                    <skinnedMesh
                      name='Object_20'
                      geometry={nodes.Object_20.geometry}
                      material={materials.MII_Pl01001_Larm_GPA_hideB_TM}
                      skeleton={nodes.Object_20.skeleton}
                    />
                    <skinnedMesh
                      name='Object_21'
                      geometry={nodes.Object_21.geometry}
                      material={materials.MII_Pl01001_RarmbreakA_GPA_ShideA_TM}
                      skeleton={nodes.Object_21.skeleton}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </>
  )
}

useGLTF.preload('/midoriya_rigged_hatchxr.glb')
